import React, { useState, useEffect } from 'react';
import { useSettings } from '../context/SettingsContext';
import { useAuth } from '../context/AuthContext';
import { supabase } from '../supabaseClient';
import TopNav from '../components/TopNav';
import Sidebar from '../components/Sidebar';
import { Save, Shield, Mail, Monitor, AlertTriangle, Send, Database, Download, Upload, Trash2, List, Activity, Users } from 'lucide-react';
import { logSystemAction } from '../utils/logger';

const Settings = () => {
  const { settings, updateSettings } = useSettings();
  const { user, forceLogoutAll } = useAuth();
  const [isSidebarOpen, setIsSidebarOpen] = useState(window.innerWidth > 768);
  const [activeTab, setActiveTab] = useState('database');
  const [testEmailTarget, setTestEmailTarget] = useState('');
  const [testEmailStatus, setTestEmailStatus] = useState('idle');
  
  const [formData, setFormData] = useState({
    idleTimeout: settings.idleTimeout || 15,
    enableReminders: settings.enableReminders ?? true,
    companyName: settings.companyName || 'TravelOps Inc.',
    currency: settings.currency || 'IDR',
    dateFormat: settings.dateFormat || 'YYYY-MM-DD',
    language: settings.language || 'en'
  });

  const [toastMessage, setToastMessage] = useState('');
  
  const [systemLogs, setSystemLogs] = useState([]);
  
  useEffect(() => {
    loadLogs();
  }, [activeTab]);

  const closeMobile = () => {
    if (window.innerWidth <= 768) setIsSidebarOpen(false);
  };

  const loadLogs = async () => {
    try {
      const { data, error } = await supabase
        .from('travelops_logs')
        .select('*')
        .order('created_at', { ascending: false })
        .limit(100);
      
      if (error) throw error;
      
      const mapped = data.map(log => ({
        id: log.id,
        timestamp: log.created_at,
        user: log.user_name,
        action: log.action,
        details: log.details
      }));
      setSystemLogs(mapped);
    } catch (err) {
      console.error('Failed to load system logs:', err);
    }
  };

  const handleSave = (e) => {
    e.preventDefault();
    updateSettings({ ...formData, idleTimeout: Number(formData.idleTimeout) });
    setToastMessage('Settings successfully saved!');
    logSystemAction(user, 'Settings Updated', 'Global settings and preferences updated.');
    setTimeout(() => setToastMessage(''), 3000);
  };

    setTestEmailStatus('sending');
    
    try {
      const response = await fetch('/api/send-email', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          to: testEmailTarget,
          subject: 'TravelOps SMTP Configuration Test',
          html: `
            <div style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
              <h2 style="color: #3b82f6;">TravelOps Notification System</h2>
              <p>Hello,</p>
              <p>If you are receiving this email, your SMTP configuration on TravelOps is working perfectly!</p>
              <hr style="border: 1px solid #eee; margin: 20px 0;" />
              <p style="font-size: 12px; color: #888;">This is an automated message generated by the TravelOps system.</p>
            </div>
          `
        })
      });

      const data = await response.json();

      if (data.success) {
        logSystemAction(user, 'SMTP Test', `Successfully sent real test email to ${testEmailTarget}`);
        setTestEmailStatus('success');
      } else {
        throw new Error(data.error || 'Failed to send email');
      }
    } catch (err) {
      console.error(err);
      alert(`SMTP Error: ${err.message}`);
      setTestEmailStatus('idle');
    }

    setTimeout(() => {
      if (testEmailStatus !== 'idle') setTestEmailStatus('idle');
    }, 5000);
  };

  const handleForceLogoutAll = () => {
    if (window.confirm("This will disconnect ALL active users except you. Continue?")) {
      forceLogoutAll();
      logSystemAction(user, 'Force Logout All', 'Invalidated all active session tokens.');
      alert("All other sessions have been terminated.");
    }
  };

  return (
    <div className="app-container fade-in">
      <Sidebar isOpen={isSidebarOpen} closeMobile={closeMobile} />
      
      <div className="main-content">
        <TopNav toggleSidebar={() => setIsSidebarOpen(!isSidebarOpen)} />
        
        <div className="content-area">
          <div className="page-container">
            <div style={{ marginBottom: '2rem' }}>
              <h1 style={{ fontSize: '1.8rem', fontWeight: '700', color: '#f8fafc', marginBottom: '0.5rem' }}>System Settings</h1>
              <p style={{ color: '#94a3b8' }}>Configure security, automation, and system administration</p>
            </div>

            <div className="tabs-container" style={{ marginBottom: '1.5rem', display: 'flex', gap: '0.5rem', borderBottom: '1px solid var(--border)', flexWrap: 'wrap' }}>
              <button className={`tab-btn ${activeTab === 'database' ? 'active' : ''}`} onClick={() => setActiveTab('database')}>
                <Database size={18} /> Database & System
              </button>
              <button className={`tab-btn ${activeTab === 'logs' ? 'active' : ''}`} onClick={() => setActiveTab('logs')}>
                <List size={18} /> System Logs
              </button>
              <button className={`tab-btn ${activeTab === 'security' ? 'active' : ''}`} onClick={() => setActiveTab('security')}>
                <Shield size={18} /> Security
              </button>
              <button className={`tab-btn ${activeTab === 'smtp' ? 'active' : ''}`} onClick={() => setActiveTab('smtp')}>
                <Mail size={18} /> SMTP & Automations
              </button>
              <button className={`tab-btn ${activeTab === 'preferences' ? 'active' : ''}`} onClick={() => setActiveTab('preferences')}>
                <Monitor size={18} /> Preferences
              </button>
            </div>

            <form onSubmit={handleSave}>
              {/* TAB: DATABASE & SYSTEM */}
              {activeTab === 'database' && (
                <div className="fade-in">
                  <div className="card" style={{ background: '#1e293b', border: '1px solid #10b98150', borderRadius: '16px', padding: '2rem', marginBottom: '1.5rem', textAlign: 'center' }}>
                    <div style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '64px', height: '64px', borderRadius: '50%', background: '#10b98120', color: '#10b981', marginBottom: '1rem' }}>
                      <Database size={32} />
                    </div>
                    <h3 style={{ margin: '0 0 0.5rem 0', color: '#10b981', fontSize: '1.5rem' }}>Cloud Database Active</h3>
                    <p style={{ color: '#cbd5e1', fontSize: '1rem', maxWidth: '500px', margin: '0 auto', lineHeight: '1.6' }}>
                      TravelOps V4 is now fully integrated with <strong>Supabase Cloud</strong>.
                      All your records (Tours, Cruises, Cashouts, Users) are securely stored and synced in real-time.
                    </p>
                    
                    <div style={{ background: '#0f172a', border: '1px solid #334155', borderRadius: '12px', padding: '1.5rem', marginTop: '2rem', textAlign: 'left', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1.5rem' }}>
                      <div>
                        <span style={{ display: 'block', color: '#94a3b8', fontSize: '0.85rem', marginBottom: '0.25rem' }}>Storage Capacity</span>
                        <strong style={{ color: '#f8fafc', fontSize: '1.1rem' }}>Unlimited (Auto-scaling)</strong>
                      </div>
                      <div>
                        <span style={{ display: 'block', color: '#94a3b8', fontSize: '0.85rem', marginBottom: '0.25rem' }}>Backups</span>
                        <strong style={{ color: '#f8fafc', fontSize: '1.1rem' }}>Automated Daily via Supabase</strong>
                      </div>
                      <div>
                        <span style={{ display: 'block', color: '#94a3b8', fontSize: '0.85rem', marginBottom: '0.25rem' }}>Local Storage Usage</span>
                        <strong style={{ color: '#10b981', fontSize: '1.1rem' }}>0 KB (Clean)</strong>
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {/* TAB: SYSTEM LOGS */}
              {activeTab === 'logs' && (
                <div className="card fade-in" style={{ background: '#1e293b', border: '1px solid #334155', borderRadius: '16px', padding: '1.5rem', overflowX: 'auto' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
                    <h3 style={{ margin: 0, color: '#f8fafc', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                      <List size={20} color="#f59e0b" /> Audit Trail
                    </h3>
                    <button type="button" onClick={loadLogs} style={{ background: '#334155', border: 'none', color: '#f8fafc', padding: '0.4rem 1rem', borderRadius: '6px', cursor: 'pointer', fontSize: '0.75rem' }}>Refresh</button>
                  </div>
                  
                  <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' }}>
                    <thead>
                      <tr style={{ background: '#0f172a', color: '#94a3b8', borderBottom: '1px solid #334155' }}>
                        <th style={{ padding: '0.75rem 1rem', textAlign: 'left', fontWeight: '500' }}>Timestamp</th>
                        <th style={{ padding: '0.75rem 1rem', textAlign: 'left', fontWeight: '500' }}>User</th>
                        <th style={{ padding: '0.75rem 1rem', textAlign: 'left', fontWeight: '500' }}>Action</th>
                        <th style={{ padding: '0.75rem 1rem', textAlign: 'left', fontWeight: '500' }}>Details</th>
                      </tr>
                    </thead>
                    <tbody>
                      {systemLogs.map(log => (
                        <tr key={log.id} style={{ borderBottom: '1px solid #334155' }}>
                          <td style={{ padding: '0.75rem 1rem', color: '#94a3b8' }}>{new Date(log.timestamp).toLocaleString()}</td>
                          <td style={{ padding: '0.75rem 1rem', color: '#3b82f6' }}>{log.user}</td>
                          <td style={{ padding: '0.75rem 1rem', color: '#f8fafc' }}>{log.action}</td>
                          <td style={{ padding: '0.75rem 1rem', color: '#cbd5e1' }}>{log.details}</td>
                        </tr>
                      ))}
                      {systemLogs.length === 0 && (
                        <tr>
                          <td colSpan="4" style={{ padding: '2rem', textAlign: 'center', color: '#64748b' }}>No system logs found.</td>
                        </tr>
                      )}
                    </tbody>
                  </table>
                </div>
              )}

              {/* TAB: SECURITY */}
              {activeTab === 'security' && (
                <div className="card fade-in" style={{ background: '#1e293b', border: '1px solid #334155', borderRadius: '16px', padding: '1.5rem' }}>
                  <h3 style={{ margin: '0 0 1.5rem 0', color: '#f8fafc', borderBottom: '1px solid #334155', paddingBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <Shield size={20} color="#3b82f6" /> Auto-Logout Configuration
                  </h3>
                  
                  <div className="form-group" style={{ maxWidth: '400px', marginBottom: '2rem' }}>
                    <label style={{ display: 'block', marginBottom: '0.5rem', color: '#94a3b8', fontSize: '0.875rem' }}>Idle Timeout (Minutes)</label>
                    <select 
                      value={formData.idleTimeout} 
                      onChange={e => setFormData({...formData, idleTimeout: e.target.value})}
                      style={{ width: '100%', background: '#0f172a', border: '1px solid #334155', color: '#f8fafc', padding: '0.75rem', borderRadius: '8px' }}
                    >
                      <option value={5}>5 Minutes</option>
                      <option value={15}>15 Minutes</option>
                      <option value={30}>30 Minutes</option>
                      <option value={60}>60 Minutes</option>
                    </select>
                  </div>

                  <h3 style={{ margin: '0 0 1.5rem 0', color: '#f8fafc', borderBottom: '1px solid #334155', paddingBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <Users size={20} color="#ef4444" /> Active Sessions Control
                  </h3>
                  <div style={{ background: '#0f172a', padding: '1.5rem', borderRadius: '8px', border: '1px solid #334155' }}>
                    <p style={{ margin: '0 0 1rem 0', color: '#94a3b8', fontSize: '0.875rem', lineHeight: '1.4' }}>
                      In case of an emergency, you can invalidate all active sessions. This will immediately force all other users currently logged into TravelOps to be logged out. Your current session will remain active.
                    </p>
                    <button type="button" onClick={handleForceLogoutAll} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', background: '#ef444420', color: '#ef4444', border: '1px solid #ef4444', padding: '0.5rem 1rem', borderRadius: '8px', cursor: 'pointer', fontWeight: '500' }}>
                      <AlertTriangle size={16} /> Force Logout All Users
                    </button>
                  </div>
                </div>
              )}

              {/* TAB: SMTP */}
              {activeTab === 'smtp' && (
                <div className="card fade-in" style={{ background: '#1e293b', border: '1px solid #334155', borderRadius: '16px', padding: '1.5rem' }}>
                  <h3 style={{ margin: '0 0 1.5rem 0', color: '#f8fafc', borderBottom: '1px solid #334155', paddingBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <Mail size={20} color="#10b981" /> SMTP Email Server
                  </h3>
                  
                  <div style={{ background: '#0f172a', padding: '1.5rem', borderRadius: '8px', border: '1px solid #10b98150', marginBottom: '1.5rem' }}>
                    <p style={{ margin: '0', color: '#cbd5e1', fontSize: '0.9rem', lineHeight: '1.5' }}>
                      <Shield size={16} color="#10b981" style={{ verticalAlign: 'middle', marginRight: '0.5rem' }}/>
                      <strong>Security Notice:</strong> SMTP configurations (Host, Port, Username, Password) are now securely managed directly on the backend server via the <code>.env</code> file. They are no longer accessible or modifiable from the frontend to prevent credential leakage.
                    </p>
                  </div>

                  <h3 style={{ margin: '2rem 0 1rem 0', color: '#f8fafc', fontSize: '1.1rem' }}>Automated Reminders</h3>
                  <label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer', color: '#cbd5e1' }}>
                    <input 
                      type="checkbox" 
                      checked={formData.enableReminders}
                      onChange={e => setFormData({...formData, enableReminders: e.target.checked})}
                      style={{ width: '1.2rem', height: '1.2rem', accentColor: '#3b82f6' }} 
                    />
                    Enable automated email reminders for Tours & Cruises
                  </label>
                  <p style={{ color: '#64748b', fontSize: '0.85rem', marginTop: '0.5rem', marginLeft: '1.7rem' }}>
                    Reminders will be sent 30, 15, 7, 5, 3, 2, 1 days before departure, on departure day, and on return day.
                  </p>

                  <div style={{ marginTop: '2rem', borderTop: '1px solid #334155', paddingTop: '1.5rem' }}>
                    <h4 style={{ margin: '0 0 1rem 0', color: '#f8fafc' }}>Test Email</h4>
                    <p style={{ color: '#94a3b8', fontSize: '0.875rem', marginBottom: '1rem' }}>Send a test email to verify SMTP configuration</p>
                    <div style={{ display: 'flex', gap: '10px', position: 'relative', alignItems: 'center', flexWrap: 'wrap' }}>
                      <input 
                        type="email" 
                        id="testEmailAddress" 
                        value={testEmailTarget}
                        onChange={(e) => setTestEmailTarget(e.target.value)}
                        placeholder="test@email.com" 
                        disabled={testEmailStatus === 'sending'}
                        style={{ position: 'relative', zIndex: 1, padding: '0.75rem', borderRadius: '8px', border: '1px solid #334155', background: '#0f172a', color: '#f8fafc', flex: '1 1 200px', maxWidth: '300px' }}
                      />
                      <button 
                        type="button" 
                        onClick={handleTestEmail} 
                        disabled={testEmailStatus === 'sending'}
                        style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', background: '#0f172a', color: testEmailStatus === 'sending' ? '#94a3b8' : '#10b981', border: `1px solid ${testEmailStatus === 'sending' ? '#334155' : '#10b981'}`, padding: '0.75rem 1.5rem', borderRadius: '8px', cursor: testEmailStatus === 'sending' ? 'not-allowed' : 'pointer', fontWeight: '500', whiteSpace: 'nowrap', transition: 'all 0.3s' }}
                      >
                        {testEmailStatus === 'sending' ? '⏳ Sending...' : '📧 Send Test'}
                      </button>
                      
                      {testEmailStatus === 'success' && (
                        <span style={{ color: '#10b981', fontSize: '0.875rem', display: 'flex', alignItems: 'center', gap: '0.25rem', animation: 'fadeIn 0.3s ease-out' }}>
                          ✓ Email Sent!
                        </span>
                      )}
                    </div>
                  </div>
                </div>
              )}

              {/* TAB: PREFERENCES */}
              {activeTab === 'preferences' && (
                <div className="card fade-in" style={{ background: '#1e293b', border: '1px solid #334155', borderRadius: '16px', padding: '1.5rem' }}>
                  <h3 style={{ margin: '0 0 1.5rem 0', color: '#f8fafc', borderBottom: '1px solid #334155', paddingBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <Monitor size={20} color="#8b5cf6" /> System Preferences
                  </h3>

                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem', marginBottom: '1.5rem' }}>
                    <div className="form-group">
                      <label style={{ display: 'block', marginBottom: '0.5rem', color: '#94a3b8', fontSize: '0.875rem' }}>Company Name</label>
                      <input type="text" value={formData.companyName} onChange={e => setFormData({...formData, companyName: e.target.value})} placeholder="TravelOps Inc." style={{ width: '100%', background: '#0f172a', border: '1px solid #334155', color: '#f8fafc', padding: '0.75rem', borderRadius: '8px' }} />
                    </div>
                    <div className="form-group">
                      <label style={{ display: 'block', marginBottom: '0.5rem', color: '#94a3b8', fontSize: '0.875rem' }}>System Language</label>
                      <select value={formData.language} onChange={e => setFormData({...formData, language: e.target.value})} style={{ width: '100%', background: '#0f172a', border: '1px solid #334155', color: '#f8fafc', padding: '0.75rem', borderRadius: '8px' }}>
                        <option value="en">English</option>
                        <option value="id">Bahasa Indonesia</option>
                      </select>
                    </div>
                  </div>

                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem', marginBottom: '1.5rem' }}>
                    <div className="form-group">
                      <label style={{ display: 'block', marginBottom: '0.5rem', color: '#94a3b8', fontSize: '0.875rem' }}>Default Currency</label>
                      <select value={formData.currency} onChange={e => setFormData({...formData, currency: e.target.value})} style={{ width: '100%', background: '#0f172a', border: '1px solid #334155', color: '#f8fafc', padding: '0.75rem', borderRadius: '8px' }}>
                        <option value="IDR">IDR - Indonesian Rupiah (Rp)</option>
                        <option value="USD">USD - US Dollar ($)</option>
                        <option value="EUR">EUR - Euro (€)</option>
                        <option value="SGD">SGD - Singapore Dollar (S$)</option>
                      </select>
                    </div>
                    <div className="form-group">
                      <label style={{ display: 'block', marginBottom: '0.5rem', color: '#94a3b8', fontSize: '0.875rem' }}>Date Format</label>
                      <select value={formData.dateFormat} onChange={e => setFormData({...formData, dateFormat: e.target.value})} style={{ width: '100%', background: '#0f172a', border: '1px solid #334155', color: '#f8fafc', padding: '0.75rem', borderRadius: '8px' }}>
                        <option value="YYYY-MM-DD">YYYY-MM-DD (2024-12-31)</option>
                        <option value="DD-MM-YYYY">DD-MM-YYYY (31-12-2024)</option>
                        <option value="MM/DD/YYYY">MM/DD/YYYY (12/31/2024)</option>
                      </select>
                    </div>
                  </div>
                </div>
              )}

              {/* SAVE BUTTON FOR TABS THAT USE IT */}
              {['security', 'smtp', 'preferences'].includes(activeTab) && (
                <div style={{ marginTop: '2rem', display: 'flex', alignItems: 'center', gap: '1rem' }}>
                  <button type="submit" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', background: '#3b82f6', color: '#fff', border: 'none', padding: '0.75rem 1.5rem', borderRadius: '8px', cursor: 'pointer', fontWeight: '500' }}>
                    <Save size={18} /> Save Settings
                  </button>
                  {toastMessage && <span style={{ color: '#10b981', fontWeight: '500' }}>{toastMessage}</span>}
                </div>
              )}
            </form>

          </div>
        </div>
      </div>
    </div>
  );
};

export default Settings;
